### ISSUE TITLE
Is PyTorch version functional?

### ISSUE THREAD

**Issue by FuriouslyCurious** [chuckyee/cardiac-segmentation#1]
Excellent paper Chuck!  Is your PyTorch Dilated Densenet version functional or still under development?

Thanks 💯

**Comment by chuckyee** [comment]
@FuriouslyCurious You can follow the progress at this repo: [link](https://github.com/chuckyee/dilated-densenet)

Mostly occupied interview for jobs, but slowly doing work on dilated densenets.
