### ISSUE TITLE
Dice coefficient value is very less.

### ISSUE THREAD

**Issue by imshubhamsingh** [chuckyee/cardiac-segmentation#11]
Hi @chuckyee, I tried running your code, and I was able to successfully run the code. But the dice score is generation during training is very less. Do you have any idea what I might be doing wrong?

![image](https://user-images.githubusercontent.com/17807743/47600023-0a134b00-d9d8-11e8-98b7-50ce701ce114.png)

**Comment by chuckyee** [comment]
The run is only on its 12th epoch -- train longer.
