### ISSUE TITLE
Contours

### ISSUE THREAD

**Issue by wellescastro** [chuckyee/cardiac-segmentation#2]
Hi!

I'm trying to use the RVSCEvaluationCode to evaluate a trained model, how can I get only the contours instead of a mask?

Thank you.

**Comment by chuckyee** [comment]
@wellescastro Maybe you already figured it out: they are accessible via the epicardium_contour and endocardium_contour attributes of the PatientData class.

**Comment by chuckyee** [comment]
@wellescastro Maybe I misunderstood -- if you want access to the predicted contours, I just committed submission.py under the scripts/ directory. I used this to generate the predicted contours for submission.

It's called like:
`python -u submission.py defaults.config --load-weights weights-final.hdf5 --datadir Test1Set --outdir test1`
