### ISSUE TITLE
Python 2 supported ?

### ISSUE THREAD

**Issue by phongnhhn92** [chuckyee/cardiac-segmentation#3]
Hello i m running your training script using Python2 but receive some errors.
![aaaaaa](https://user-images.githubusercontent.com/11288381/30630336-23a5088c-9e1b-11e7-90c4-29893b466080.png)
Is this code built on python 3 ?

**Comment by xixinxin** [comment]
I also met this problem, but fixed on python 2.7

**Comment by chuckyee** [comment]
@phongnhhn92 @xixinxin 

I changed the construction of the tuple -- should work now for python < 2.7.
Lmk if it doesn't.
