### ISSUE TITLE
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options" when import patient, models from rvseg

### ISSUE THREAD

**Issue by tianqig** [chuckyee/cardiac-segmentation#7]
Hi

I am using Anaconda on Mac, Python 2.7.  My installation looked ok, no error, but failed in 
import rvseg:

```
>>> import matplotlib.pyplot as plt
>>> from rvseg import patient, models
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rvseg/models/__init__.py", line 1, in <module>
   from .convunet import unet
  File "rvseg/models/convunet.py", line 3, in <module>
    from keras.layers import Input, Conv2D, Conv2DTranspose

```
A few lines  deleted here, 

```
File "/Users/Tan/anaconda/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.DescriptorProto.ExtensionRange.options"
```

Not sure why? I noticed that I have  three versions of protobuf installed,
protobuf                  3.3.2                    py27_0    conda-forge
protobuf                  3.4.0                     <pip>
protobuf                  3.2.0                     <pip>

But based on the requirements.txt, it should be protobuf==3.3.0

Wonder if the error was caused because of the protobuf version ?

Thanks

David

**Comment by tianqig** [comment]
I uninstalled the 3 installed protobuf above, then installed 3.4.1 version, also updated my
tensorflow to  1.4.0 

```
>>> import matplotlib.pyplot as plt
>>> from rvseg import patient, models
```

The error message now:

` File "/Users/Tian/anaconda/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)


KeyError: "Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start"`


Any suggestions? Thanks

**Comment by chuckyee** [comment]
I assume this is a TF problem. Did you already follow the suggestions here: https://github.com/tensorflow/tensorflow/issues/14689 ?

I don't have any additional insight beyond googling.

**Comment by tianqig** [comment]
Thanks, the problem was fixed after installing the right versions of 
protobuf 3.3.0  and tensorflow 1.2.1
